#!/bin/bash

GROMPP=`which grompp`
GDENS=../../g_density
# the file included.sh is generated by cmake and contains 
# some environment variables to be used in this script

if [ -z $GROMPP ] ; then 
	echo "could not find grompp, cannot continue."  ; exit
fi

if [ -z $GDENS ] ; then 
	echo "could not find g_density, cannot continue."  ; exit
fi

echo "g_density needs a .tpr file, let's create it now...."
$GROMPP -f grompp.mdp -p topol.top -c ccl4-h2o.gro  -maxwarn 10  -o ccl4-h2o.tpr> grompp.log 2>&1 
echo "0 4 5" > masscom.dat
echo "Using $GDENS ..."
if [ -a ccl4-h2o.tpr ] ; then 
        name=dens_H2O_atomic_m ; echo "Intrinsic mass density profile w.r.t. water -> $name.xvg"
	echo "SOL SOL CCl4"  | $GDENS  -intrinsic -dens mass -f ccl4-h2o.gro -ng 3 -center -sl 200 -s ccl4-h2o.tpr  -o $name.xvg  > $name.log 2>&1 
        name=dens_CCl4_atomic_m ; echo "Intrinsic mass density profile w.r.t. ccl4-> $name.xvg"
	echo "CCl4 SOL CCl4" | $GDENS  -intrinsic -dens mass -f ccl4-h2o.gro -ng 3 -center -sl 200 -s ccl4-h2o.tpr  -o $name.xvg  > $name.log   2>&1 
        name=dens_H2O_atomic_n ; echo "Intrinsic number density profile w.r.t. water -> $name.xvg"
	echo "SOL SOL CCl4"  | $GDENS  -intrinsic -dens number -f ccl4-h2o.gro -ng 3 -center -sl 200 -s ccl4-h2o.tpr    -o $name.xvg  > $name.log   2>&1 
        name=dens_CCl4_atomic_n ; echo "Intrinsic number density profile w.r.t. ccl4 -> $name.xvg"
	echo "CCl4 SOL CCl4" | $GDENS  -intrinsic -dens number -f ccl4-h2o.gro -ng 3 -center -sl 200 -s ccl4-h2o.tpr    -o $name.xvg  > $name.log  2>&1 
        name=dens_H2O_atomicMC_m ; echo "Intrinsic mass density profile w.r.t. water with Monte Carlo normalization-> $name.xvg"
	echo "SOL SOL CCl4"  | $GDENS  -intrinsic -MCnorm -dens mass -f ccl4-h2o.gro -ng 3 -center -sl 200 -s ccl4-h2o.tpr  -o $name.xvg  > $name.log 2>&1 
        name=dens_H2O_molecularMC_m ; echo "Intrinsic molecular mass density profile w.r.t. water with Monte Carlo normalization-> $name.xvg"
	echo "SOL SOL CCl4"  | $GDENS  -intrinsic -MCnorm -dens mass -com -f ccl4-h2o.gro -ng 3 -center -sl 200 -s ccl4-h2o.tpr  -o $name.xvg  > $name.log 2>&1 
else 
	echo "Some errors probably occurred running grompp. Please have a look at grompp.log"

fi  



