#!/bin/bash

GROMPP=`which grompp`
GDENS=`which gitim`
# the file included.sh is generated by cmake and contains 
# some environment variables to be used in this script
source included.sh

if [ -z $GROMPP ] ; then 
	echo "could not find grompp, cannot continue."  ; exit
fi

if [ -z $GDEMS] ; then 
	echo "could not find gitim in the path, cannot continue." 
	exit
fi

echo "gitim needs a .tpr file, let's create it now...."
$GROMPP -f grompp.mdp -p micelle.top -c micelle.gro  -o micelle.tpr -maxwarn 20 > grompp.log 2>&1 
echo "0 4 5" > masscom.dat
echo "Using $GDENS ..."
if [ -a micelle.tpr ] ; then 
        name=dens_DPC_atomic_m ; echo "Intrinsic mass density profile w.r.t. DPC -> $name.xvg"
	echo "DPC SOL DPC"  | $GDENS  -intrinsic -dens mass -f micelle.gro -ng 3 -center -sl 200 -s micelle.tpr -MCnorm -alpha 0.2 -geometry sphere -o $name.xvg  > $name.log 2>&1 
else 
	echo "Some errors probably occurred running grompp. Please have a look at grompp.log"

fi  



